import { Frequency, MintType, PlanType } from "../../types/PlanType";

export const PlantListing: PlanType[] = [
  {
    planId: 1,
    hub: 55,
    hubName: "$55 | 300 | Base Package | " + Frequency.Daily,
    capacity: 300,
    durationInMonths: 25,
    frequency: Frequency.Daily,
    growth: 250,
    type: MintType.Manual,
    remarks: "Base Package",
    removable: false,
  },
  {
    planId: 2,
    hub: 165,
    hubName: "$165 | 900 | Base Package | " + Frequency.Daily,
    capacity: 900,
    durationInMonths: 25,
    frequency: Frequency.Daily,
    growth: 250,
    type: MintType.Manual,
    remarks: "Base Package",
    removable: false,
  }//,
  // {
  //   planId: 3,
  //   hub: 1650,
  //   hubName: "$1650 | 16000 | Travel Package | " + Frequency.Daily,
  //   capacity: 16000,
  //   durationInMonths: 25,
  //   frequency: Frequency.Daily,
  //   growth: 250,
  //   type: MintType.Manual,
  //   remarks: "Base Package",
  // },
  // {
  //   planId: 4,
  //   hub: 666,
  //   hubName: "$600 | 6666 | Base Package | " + Frequency.Holding,
  //   capacity: 6666,
  //   durationInMonths: 18,
  //   growth: 300,
  //   frequency: Frequency.Holding,
  //   type: MintType.Auto,
  //   remarks: "Special",
  //   endDate: "31-12-9999",
  // },
  // {
  //   planId: 11,
  //   hub: 666,
  //   hubName: "$666 | 6666 | Base Package | " + Frequency.Holding,
  //   capacity: 6666,
  //   durationInMonths: 24,
  //   growth: 300,
  //   frequency: Frequency.Holding,
  //   type: MintType.Auto,
  //   remarks: "Special",
  //   endDate: "31-12-9999",
  // },
  // {
  //   planId: 5,
  //   hub: 666,
  //   hubName: "$666 | 6666 | Base Package | " + Frequency.HalfYearly,
  //   capacity: 6666,
  //   durationInMonths: 24,
  //   growth: 300,
  //   frequency: Frequency.HalfYearly,
  //   type: MintType.Auto,
  //   remarks: "Special",
  //   endDate: "31-12-9999",
  // },
  // {
  //   planId: 6,
  //   hub: 550,
  //   hubName: "$550 | $5555 | Kohinoor 2.0 | " + Frequency.HalfYearly,
  //   capacity: 5555,
  //   durationInMonths: 30,
  //   growth: 350,
  //   frequency: Frequency.HalfYearly,
  //   type: MintType.Auto,
  //   remarks: "Special",
  //   endDate: "31-12-9999",
  // },
  // {
  //   planId: 7,
  //   hub: 900,
  //   hubName: "$900 | $5500 | Diamond | " + Frequency.HalfYearly,
  //   capacity: 5500,
  //   durationInMonths: 30,
  //   growth: 350,
  //   frequency: Frequency.HalfYearly,
  //   type: MintType.Auto,
  //   remarks: "Special",
  //   endDate: "31-12-9999",
  // },
  // {
  //   planId: 8,
  //   hub: 666,
  //   hubName: "$666 | 6666 | Pearl Package | " + Frequency.Quarterly,
  //   capacity: 6666,
  //   durationInMonths: 18,
  //   growth: 300,
  //   frequency: Frequency.Quarterly,
  //   type: MintType.Auto,
  //   remarks: "Special",
  //   endDate: "31-12-9999",
  // },
];